name: auto_start_permission
description: "Flutter plugin for setting up auto start permission - ANDROID ONLY"
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.khapilov.auto_start_permission
        pluginClass: AutoStartPermissionPlugin
