name: auto_start_permission
description: "Flutter plugin for setting up auto start permission - ANDROID ONLY"
homepage: https://github.com/RossHS/auto_start_permission
version: 1.0.1

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.khapilov.auto_start_permission
        pluginClass: AutoStartPermissionPlugin
